### ISSUE TITLE
vale server crashes

### ISSUE THREAD

**Issue by slowlydev** [koozz/zed-vale#2]
Thanks for writing this zed extension, I have also tried to do this myself but I did not quite succeed and you beat me to it 😅

But I seem to be getting some errors in the language server logs when hitting `⌘+.` to fix the spelling issues.

Here the logs:
```
initialized!
configuration changed!
stderr: thread 'main' panicked at src/server.rs:318:61:
stderr: called `Option::unwrap()` on a `None` value
stderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Sadly it seems to be an issue with the vale language server itself. Have you also experienced this issue?

**Comment by koozz** [comment]
Hi @slowlydev, the language server does crash from time to time, but it does help to have a configuration in place and run `vale sync`. I do get errors and suggestions just like running vale from the commandline.

**Comment by slowlydev** [comment]
Okay hm I will look into it thanks for the response
