### ISSUE TITLE
Missing permission for vale-ls executable

### ISSUE THREAD

**Issue by lvignoli** [koozz/zed-vale#3]
On a fresh install, vale-ls was failing to start per Zed logs.
I had to manually add execution permission to the binary to fix it
```
chmod u+x "/Users/me/Library/Application Support/Zed/extensions/work/vale/vale-ls-v0.3.7/vale-ls"
```

#### Specs
Zed: v0.145.0 (Zed Preview)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

**Comment by koozz** [comment]
@lvignoli, thank you for filing an issue.
I have downloaded the same vale-ls archive from the [releases page](https://github.com/errata-ai/vale-ls/releases) but it does have the executable bit.
Could it be that your Mac prevented it from being executable as some (sane) security measure?

**Comment by lvignoli** [comment]
Hi, I was away sorry.
I guess so, but if so, that was silent. Maybe Zed HTTP clients downloads files in a peculiar way?

**Comment by koozz** [comment]
I will try a clean install (one of these days).

**Comment by osiewicz** [comment]
I've just ran into this as well. There's https://docs.rs/zed_extension_api/latest/zed_extension_api/fn.make_file_executable.html API that we could use to fix that.
