### ISSUE TITLE
Where is `vale` binary installed?

### ISSUE THREAD

**Issue by LiveDuo** [koozz/zed-vale#6]
Have installed the extension through Zed but can't run `vale sync`. I'm getting `zsh: command not found: vale`.

Where should the `vale` binary be installed?

**Comment by koozz** [comment]
This only installs vale-ls in the extensions folder, for me (Mac OS) that boils down to:
`~/Library/Application Support/Zed/extensions/work/vale/vale-ls-v0.3.8/vale-ls`

You can install the CLI by following the official instructions at https://vale.sh/docs/vale-cli/installation/

Do you think the vale CLI is also needed in the plugin? And how would that look like?

**Comment by LiveDuo** [comment]
@koozz I was trying to setup the plugin to work. I still can't see any integrations with `zed` while `vale` CLI tool works.

**Comment by koozz** [comment]
@LiveDuo, do you have a [.vale.ini](https://vale.sh/docs/topics/config/) in the root of your project?

Example would be `.vale.ini`:

```ini
StylesPath = styles

Vocab = Vale

[*]
BasedOnStyles = Vale
```

**Comment by LiveDuo** [comment]
@koozz Yeap, I tried both the one from `Readme` and the example one in your last comment.

**Comment by LiveDuo** [comment]
@koozz Working now. Seems like Zed have to be restarted after running `vale sync`.

One more question:
Can `vale` be configured to run on specific file extensions and / or folders?

**Comment by andreacfromtheapp** [comment]
> Do you think the vale CLI is also needed in the plugin? And how would that look like?

please don't :D vale-ls is great to manage with the extension but the tool itself is out of scope
